name: Kuresel Mufredat Otonom Kazici

on:
  schedule:
    - cron: '0 0 * * *' # Her gece 03:00'te (TSİ) otomatik çalışır
  workflow_dispatch: # İstediğiniz zaman el ile de çalıştırabilmeniz için

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
    - name: Depoyu Bilgisayara Cek
      uses: actions/checkout@v3

    - name: Python Ortamini Kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Gerekli Kutuphaneleri Yukle
      run: |
        pip install requests beautifulsoup4

    - name: Kazima Motorunu Atesle
      run: |
        python otonom_motor.py

    - name: Guncellenen JSON Verilerini Depoya Kaydet
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add veri.json
        git commit -m "Otonom Mufredat Guncellendi [AKTS + Tum Dersler]" || exit 0
        git push
